### ISSUE TITLE
[bug] Displaying incorrect values for Owens Status

### ISSUE THREAD

**Issue by brianmcmichael** [AweSim-OSC/osc-systemstatus#38]
After update to `awesim-test`, Owens is displaying incorrect values for number of nodes and number of cores.

This error is only occurring on `apps-test.awesim.org` and not on `ondemand-test.hpc.osc.edu`

![owenserror](https://cloud.githubusercontent.com/assets/2374718/23908065/52a3818e-08a9-11e7-8fa0-0006dae398a2.png)

**Comment by ericfranz** [comment]
Can't reproduce.
