### ISSUE TITLE
CPU Heatmaps

### ISSUE THREAD

**Issue by brianmcmichael** [AweSim-OSC/osc-systemstatus#4]
[gweb](http://cts05.osc.edu/gweb/) includes the ability to display a heatmap of a particular cluster.

This is rendered clientside by datapoints provided by gweb.

![heatmap](https://cloud.githubusercontent.com/assets/2374718/10640818/706825be-77e4-11e5-8ff3-0ed85f37330e.png)

Not sure if this information is of any value or a novelty. If useful, this could potentially be embedded into the system status app.

Additional details: http://ganglia.info/?p=464

**Comment by ericfranz** [comment]
Not doing.
