### ISSUE TITLE
Port this to OOD

### ISSUE THREAD

**Issue by nickjer** [AweSim-OSC/osc-systemstatus#43]
Martin Cuma brought up a feature request along the lines of what this app delivers.

His use-case is for users to review the current utilization across the clusters at the center to determine the optimal cluster to submit jobs to for quicker turn-around.

Thoughts @basilgohar?

**Comment by ericfranz** [comment]
Closing this issue as https://github.com/AweSim-OSC/osc-systemstatus/issues/56 is more actionable but related.
