### ISSUE TITLE
Consider adding OSC node status graphs.

### ISSUE THREAD

**Issue by brianmcmichael** [AweSim-OSC/osc-systemstatus#44]
Node status (as opposed to CPU status) is now available in OSC Ganglia.

https://ganglia.osc.edu/graph_all_periods.php?h=owens-batch.ten.osc.edu&m=boottime&r=hour&s=by%20name&hc=4&mc=2&st=1494617396&g=moab_nodes_report&z=large&c=Owens

Should we consider adding it to System Status? Is this available for all clusters?

Would need ingest and design.

**Comment by ericfranz** [comment]
Using node utilization. Can revisit adding other graphs later if requested.
