### ISSUE TITLE
Number overlaps edge of bar graph making it illegible

### ISSUE THREAD

**Issue by nickjer** [AweSim-OSC/osc-systemstatus#48]
The number of queued jobs overlaps the edge of the corresponding bar making it hard to read:

![image](https://user-images.githubusercontent.com/4260509/35159531-8dacef5a-fd08-11e7-8559-6d8357801128.png)

That image shows `127` jobs queued, but at first glance it looks like `12` jobs queued.

**Comment by ericfranz** [comment]
The fix should be to add the total number after the bar on the right. The fix might require modifying the html of the entire "row".

http://www.perceptualedge.com/example1.php

![](http://www.perceptualedge.com/images/example1solution.gif)
