### ISSUE TITLE
Replace Rails with simpler Sinatra based app

### ISSUE THREAD

**Issue by ericfranz** [AweSim-OSC/osc-systemstatus#51]
Goals:

- smaller code base can be a good example of a "status" style app used in production at OSC
- reduce rpm build time
- faster load time

Suggestions:

- unless there is already polling, use Turbolinks (see ood-sacct for example of this)
- any use of ood_appkit for loading cluster config, etc. code could be copied to the app itself for right now (and then we can identify what we should add to ood_core or ood_support)
- could use this app to explore alternative js options (so compare Turbolinks version with a vue.js version with a react.js version)

**Comment by ericfranz** [comment]
@AriettaZ for Turbolinks, you will need to do https://github.com/turbolinks/turbolinks/blob/master/README.md#setting-a-root-location and set the root location to be the PASSENGER_BASE_URI which I believe is an environment variable. That way it treats links to the same domain and port but not at the same base uri as an external site.

I don't believe there is any polling on the system status app, so adding this shouldn't interfere. https://github.com/turbolinks/turbolinks is a quick way to get lots of the benefit offered by "single page web apps" without writing a lot of extra cilent-side code. Also, it means it would be an option for actually rendering each graph only when the user clicks on it.

**Comment by brianmcmichael** [comment]
Polling is done via javascript at https://github.com/AweSim-OSC/osc-systemstatus/blob/master/app/assets/javascripts/clusters.js.coffee#L10-L20
