### ISSUE TITLE
Update to use the new parsed and formatted messages.

### ISSUE THREAD

**Issue by brianmcmichael** [AweSim-OSC/osc-systemstatus#6]
The current message of the day on the system status app displays the complete and autolinked `motd`.

We have a method of parsing and displaying these on the dashboard at https://github.com/AweSim-OSC/awesim-dev-dashboard/blob/master/lib/motd_file.rb

We may want to consider reusing this code and updating the system status app as time and interest permit.

**Comment by ericfranz** [comment]
motd has been removed
