### ISSUE TITLE
Show number of GPU's being used at any given moment for each cluster (out of the total number of GPUs available)

### ISSUE THREAD

**Issue by ericfranz** [AweSim-OSC/osc-systemstatus#68]
Goal: report 4 numbers:

1. Number of GPUs unallocated (this is the free GPUs you have identified)
2. Number of full nodes available that contain one or more GPUs available
3. Number of jobs that have requested one or more GPUs that are currently queued
4. Number of GPUs requested by jobs that are currently queued

From INC0339970

>I am writing this email to give somewhat feedback on ondemand.osc.edu website. In the website, I usually check Clusters > System Status section to check which cluster is least busy before I submit a job. I use the cluster that is least busy to shorten the queued time. This has worked pretty well. However, if I want to use GPU to boost up my calculation, it is hard to know how many GPUs are being used at the moment. As there are much smaller number of GPUs than CPUs, my jobs were queued much longer than my expectation based on System Status. So, I was wondering if we can have 'GPU System Status' or something that tells how many GPUs are being used and how many GPU runs are queued etc. GPGPU being more and more popular, I think this kind of update will help people including myself who wants to use GPU in OSC a lot

**Comment by ericfranz** [comment]
![screen 2019-03-13 at 10 17 22 AM](https://user-images.githubusercontent.com/512333/54285968-53c09480-4579-11e9-9603-05bab7351ccc.png)

**Comment by ericfranz** [comment]
Maybe call out how many free nodes/procs/gpus there are:

![screen 2019-03-13 at 10 21 45 AM](https://user-images.githubusercontent.com/512333/54286275-e19c7f80-4579-11e9-86d2-f6e877c2838c.png)

**Comment by achalker** [comment]
Very cool.


-------------------------
Alan Chalker, Ph.D.
alanc@osc.edu<mailto:alanc@osc.edu>
614-247-8672

**Comment by achalker** [comment]
While we’re at it, should we also do the same for the big-mem nodes?


-------------------------
Alan Chalker, Ph.D.
alanc@osc.edu<mailto:alanc@osc.edu>
614-247-8672

**Comment by ericfranz** [comment]
The states of all the GPUs we can get a list of nodes with GPUs in XML format:

    pbsnodes -s pitzer-batch.ten.osc.edu -x :gpu

This produes a bunch of nodes like:

```
  <Node>
    <name>p0256</name>
    <state>job-exclusive</state>
    <power_state>Running</power_state>
    <np>40</np>
    <properties>r740,ib-i4l1s11,ib-i4,eth-pitzer-rack06h1,eth-pitzer-rack06b1,pitzer-rack07,pitzer,gpu,v100,pfsdir,vis,ime</properties>
    <ntype>cluster</ntype>
    <jobs>0-39/420639.pitzer-batch.ten.osc.edu</jobs>
    <status>opsys=linux,uname=Linux p0256.ten.osc.edu 3.10.0-862.11.6.el7.x86_64 #1 SMP Fri Aug 10 16:55:11 UTC 2018 x86_64,sessions=15376 184725 298901,nsessions=3,nusers=3,idletime=86941,totmem=445132568kb,availmem=430368088kb,physmem=394800924kb,ncpus=40,loadave=40.11,gres=,netload=2947886376928,size=881223036kb:892434684kb,state=free,varattr= ,cpuclock=Fixed,macaddr=24:6e:96:dd:63:34,version=6.1.2,rectime=1552502390,jobs=420639.pitzer-batch.ten.osc.edu</status>
    <mom_service_port>15002</mom_service_port>
    <mom_manager_port>15003</mom_manager_port>
    <gpus>2</gpus>
    <gpu_status>gpu[1]=gpu_id=0000:D8:00.0;gpu_pci_device_id=498340062;gpu_pci_location_id=0000:D8:00.0;gpu_product_name=Tesla V100-PCIE-16GB;gpu_memory_total=16130 MB;gpu_memory_used=11 MB;gpu_mode=Exclusive_Process;gpu_state=Unallocated;gpu_utilization=0%;gpu_memory_utilization=0%;gpu_ecc_mode=Disabled;gpu_temperature=24 C,gpu[0]=gpu_id=0000:3B:00.0;gpu_pci_device_id=498340062;gpu_pci_location_id=0000:3B:00.0;gpu_product_name=Tesla V100-PCIE-16GB;gpu_memory_total=16130 MB;gpu_memory_used=554 MB;gpu_mode=Exclusive_Process;gpu_state=Exclusive;gpu_utilization=75%;gpu_memory_utilization=17%;gpu_ecc_mode=Disabled;gpu_temperature=49 C;gpu_display=Enabled,gpu_display=Enabled,driver_ver=410.79,timestamp=Wed Mar 13 14:39:50 2019</gpu_status>
    <total_sockets>2</total_sockets>
    <total_numa_nodes>2</total_numa_nodes>
    <total_cores>40</total_cores>
    <total_threads>40</total_threads>
    <dedicated_sockets>0</dedicated_sockets>
    <dedicated_numa_nodes>0</dedicated_numa_nodes>
    <dedicated_cores>40</dedicated_cores>
    <dedicated_threads>40</dedicated_threads>
  </Node>
```

The complexity comes in that this node has 2 GPUs and the state of each GPU is in the gpu_status string, so parsing is slightly more challenging.

These commands also seems to do the trick:

```
efranz@pitzer-login01:~$ function gpu_states { pbsnodes -s $1 :gpu | ruby -n -e 'puts $_.scan(/gpu_state=(\w+)/)'; }
efranz@pitzer-login01:~$ echo "Pitzer: $(gpu_states pitzer-batch.ten.osc.edu | grep 'Unallocated' | wc -l)/$(gpu_states pitzer-batch.ten.osc.edu | wc -l)"
Pitzer: 30/64
efranz@pitzer-login01:~$ echo "Owens: $(gpu_states owens-batch.ten.osc.edu | grep 'Unallocated' | wc -l)/$(gpu_states owens-batch.ten.osc.edu | wc -l)"
Owens: 3/158
```

Its better in the context of a request to do one exec to get the XML though (or the non XML output) and parse the resulting data, than doing multiple execs.

**Comment by ericfranz** [comment]
Yes we should absolutely do big mem though I don't know the easiest approach to query that. I'll open a separate issue to track that work.

**Comment by ericfranz** [comment]
Note that even with this reporting it doesn't guarantee that you will get the queue time you want. Let say for example, PItzer above has 30/64 GPUs in use, but because Pitzer has 32 GPU nodes with two GPUs each, **what if all 30 jobs have reserved the entire node and one GPU**. In this case, while there are 34 GPUs that have the state `Unallocated`, there actually might only be 1 node and 2 GPUs available. **This means that multiple users trying to request that resource will be stymied by queue times, and using the metric `30/64` is not helpful to determine which cluster to submit a GPU job to in order to get the shortest queue time.**

In fact this is the example we have in the above node XML. There we have node `p0256` with 2 GPUs, one in the state `Unallocated` and the other in the state `Exclusive` and one job `420639.pitzer-batch.ten.osc.edu` is running on it.

I think you can take `<dedicated_threads>40</dedicated_threads>` over `<total_threads>40</total_threads>` (but not dedicated_cores, total_cores) to determine how many cores are reserved.

For example, here is a node o0700 that has 3 jobs running on it, the GPU is in use, but not all the cores are in use:

```
o0700
     state = free
     power_state = Running
     np = 28
     properties = broadwell-ep,r730,ib-i2l1s02,ib-i2,eth-owens-rack12h1,owens-rack12,owens,gpu,p100,vis,pfsdir,ime,beegfs
     ntype = cluster
     jobs = 0/4862755.owens-batch.ten.osc.edu,2-3,5-10/4890615.owens-batch.ten.osc.edu,11-18/4890616.owens-batch.ten.osc.edu
     status = opsys=linux,uname=Linux o0700.ten.osc.edu 3.10.0-862.25.3.el7.x86_64 #1 SMP Wed Nov 7 05:19:18 EST 2018 x86_64,sessions=7947 168859 171444 171527 179812 180030 180031,nsessions=7,nusers=4,idletime=1374883,totmem=182247356kb,availmem=175375756kb,physmem=131915712kb,ncpus=28,loadave=5.09,gres=,netload=1293332383259,size=909151504kb:909207804kb,state=free,varattr= ,cpuclock=Fixed,macaddr=14:18:77:60:d1:58,version=6.1.2,rectime=1552504283,jobs=4862755.owens-batch.ten.osc.edu 4890615.owens-batch.ten.osc.edu 4890616.owens-batch.ten.osc.edu
     mom_service_port = 15002
     mom_manager_port = 15003
     gpus = 1
     gpu_status = gpu[0]=gpu_id=0000:04:00.0;gpu_pci_device_id=368578782;gpu_pci_location_id=0000:04:00.0;gpu_product_name=Tesla P100-PCIE-16GB;gpu_memory_total=16280 MB;gpu_memory_used=513 MB;gpu_mode=Default;gpu_state=Shared;gpu_utilization=16%;gpu_memory_utilization=1%;gpu_ecc_mode=Enabled;gpu_single_bit_ecc_errors=0;gpu_double_bit_ecc_errors=0;gpu_temperature=31 C,gpu_display=Enabled,driver_ver=410.79,timestamp=Wed Mar 13 15:11:17 2019
     total_sockets = 2
     total_numa_nodes = 2
     total_cores = 28
     total_threads = 28
     dedicated_sockets = 0
     dedicated_numa_nodes = 0
     dedicated_cores = 0
     dedicated_threads = 17
```

This line shows 17 cores in use: 

    jobs = 0/4862755.owens-batch.ten.osc.edu,2-3,5-10/4890615.owens-batch.ten.osc.edu,11-18/4890616.owens-batch.ten.osc.edu

Which corresponds to 17 requested ppn:

```
efranz@owens-login01:~$ qstat -f 4862755.owens-batch.ten.osc.edu | grep Resource_List.nodes
    Resource_List.nodes = 1:ppn=1:gpus=1:default
efranz@owens-login02:~$ qstat -f 4890615.owens-batch.ten.osc.edu | grep Resource_List.nodes
    Resource_List.nodes = 1:ppn=8
efranz@owens-login01:~$ qstat -f 4890616.owens-batch.ten.osc.edu | grep Resource_List.nodes
    Resource_List.nodes = 1:ppn=8
```

**Comment by ericfranz** [comment]
This will take some more thought. Lets put this on temporary hold.

**Comment by ericfranz** [comment]
This needs more design, but based on offline discussion the idea is knowing how many jobs that have requested gpus:

1. are currently running
2. are currently queued (or held)

Same with big mem nodes: how many jobs have requested big mem that:

1. are currently running
2. are currently queued (or held)

**Comment by ericfranz** [comment]
This should be available in the native hash attribute of the Info object returned for each job - hopefully this includes "gpus_reserved".

Using qstat -f you can see what this looks like. On Owens there is only 1 GPU per node so you have results like this:

```
    efranz@owens-login01:~$ qstat -f | grep gpus_reserved
        gpus_reserved = o0675:0
        gpus_reserved = o0676:0
        gpus_reserved = o0767:0+o0742:0+o0703:0+o0704:0
```

Notice each gpu node reserved is delimited using +. The gpu # in use is specified by the 0. So this matters on Pitzer:

```
efranz@pitzer-login03:~$ qstat -f | grep gpus_reserved
    gpus_reserved = p0243:0
    gpus_reserved = p0244:0
    gpus_reserved = p0244:1
    gpus_reserved = p0250:0
    gpus_reserved = p0250:1
    gpus_reserved = p0245:0
    gpus_reserved = p0245:1
    gpus_reserved = p0232:0-1
    gpus_reserved = p0240:0-1
    gpus_reserved = p0235:0-1
    gpus_reserved = p0225:0-1
    gpus_reserved = p0230:0-1
    gpus_reserved = p0242:0-1
```

Here a job that has reserved both GPUs on a GPU node on Pitzer shows a range: `p0242:0-1`. 

I wonder if there were three or more gpus, if instead of a range it would use comma delmited numbers, `0,2` or a mixture `0,2-3`. But that would require some investigation.

As far as jobs queued that requested, gpus, qstat -f shows `Resource_List.feature = gpu` and `Resource_List.nodect = 1` and `Resource_List.nodes = 1:ppn=40:gpus=2`. But for queued jobs it looks like parsing `Resource_List.nodes` value to see if 2 gpus per node or one gpu per node was requested or not is required.

**Comment by ericfranz** [comment]
Report 4 numbers:

1. Number of GPUs unallocated (this is the free GPUs you have identified)
2. Number of full nodes available that contain one or more GPUs available
3. Number of jobs that have requested one or more GPUs that are currently queued
4. Number of GPUs requested by jobs that are currently queued
